# config.yaml
datasets:
  ingresos:
    table_name: "ingresos"
    year_column: "ANO_DOC"
    read_options:
      format: "csv"
      header: true
      delimiter: ","
      encoding: "utf-8-sig"
    diccionario:
      url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/Ingresos_Diccionario.csv"
      filename: "Ingresos_Diccionario.csv"
    historico:
      - anio: 2012
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2012-Ingreso.csv"
        filename: "2012-Ingreso.csv"
      - anio: 2013
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2013-Ingreso.csv"
        filename: "2013-Ingreso.csv"
      - anio: 2014
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2014-Ingreso.csv"
        filename: "2014-Ingreso.csv"
      - anio: 2015
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2015-Ingreso.csv"
        filename: "2015-Ingreso.csv"
      - anio: 2016
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2016-Ingreso.csv"
        filename: "2016-Ingreso.csv"
      - anio: 2017
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2017-Ingreso.csv"
        filename: "2017-Ingreso.csv"
      - anio: 2018
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2018-Ingreso.csv"
        filename: "2018-Ingreso.csv"
      - anio: 2019
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2019-Ingreso.csv"
        filename: "2019-Ingreso.csv"
      - anio: 2020
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2020-Ingreso.csv"
        filename: "2020-Ingreso.csv"
      - anio: 2021
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2021-Ingreso.csv"
        filename: "2021-Ingreso.csv"
      - anio: 2022
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2022-Ingreso.csv"
        filename: "2022-Ingreso.csv"
      - anio: 2023
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2023-Ingreso.csv"
        filename: "2023-Ingreso.csv"
      - anio: 2024
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2024-Ingreso.csv"
        filename: "2024-Ingreso.csv"
      - anio: 2025
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2025-Ingreso-Mensual.csv"
        filename: "2025-Ingreso-Mensual.csv"
        live_update: true
      - anio: 2026
        url: "https://fs.datosabiertos.mef.gob.pe/datastorefiles/2026-Ingreso-Mensual.csv"
        filename: "2026-Ingreso-Mensual.csv"
        live_update: true

  sismepre:
    year_column: "ANO_APLICACION"
    read_options:
      format: "csv"
      header: true
      delimiter: ","
      encoding: "utf-8-sig"
    diccionarios:
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=72019db9-35d5-4abb-8c6c-a6bac1d1792a"
        filename: "rentas_preguntas_diccionario.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=4e2257ee-4a6d-46ce-bca2-6d0d93165d24"
        filename: "rentas_estadistica_diccionario.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=66100448-c6c4-4919-a551-3d57a8e13b42"
        filename: "rentas_formulario_diccionario.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=eb5f7a3e-6b54-4461-a361-cacee9991313"
        filename: "rentas_respuestas_diccionario.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=f2d375f8-9f67-4bf8-849f-9082e7a6eb89"
        filename: "rentas_entidad_estado_diccionario.csv"
        required: false
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=d71e1a4a-81b0-488d-beda-619ab44b279f"
        filename: "rentas_ano_aplicacion_diccionario.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=1fa788c6-3569-4405-8862-36efe3afbcd7"
        filename: "rentas_esat_estadistica_atm_diccionario.csv"

    archivos:
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=96b53d87-dc98-41ee-8fea-3b45e6201942"
        filename: "rentas_preguntas.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=69abaf52-1d36-4efb-86d0-38af739896c7"
        filename: "rentas_estadistica.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=5473b6da-2453-48d0-bc50-e38afc8e732c"
        filename: "rentas_formulario.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=52f97ee4-6a52-465a-98e8-7e5ba8328b30"
        filename: "rentas_esat_estadistica_atm.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=d03c11b0-3c33-4c61-85fc-507bbcaf9cae"
        filename: "rentas_respuestas.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=d107f21c-686a-4217-ac0c-9f96b4f00df0"
        filename: "rentas_ano_aplicacion.csv"
      - url: "https://api.datosabiertos.mef.gob.pe/DatosAbiertos/v1/datastore_search?resource_id=5989e884-f198-4a92-817d-890d71e8984a"
        filename: "rentas_entidad_estado.csv"

  renamu:
      table_name: "renamu"
      year_column: "Año"
      read_options:
        format: "csv"
        header: true
        delimiter: ";"
        encoding: "utf-8-sig"
        multiLine: true
      diccionario:
        url: "https://www.inei.gob.pe/media/DATOS_ABIERTOS/RENAMU/DICCIONARIO/2022/Diccionario.pdf"
        filename: "renamu_diccionario_2022.pdf"
      data_completa:
        url: "https://www.inei.gob.pe/media/DATOS_ABIERTOS/RENAMU/DATA/2022.zip"
        filename: "renamu_2022.zip"

  categorias_municipalidades:
    table_name: "categorias_municipalidades"
    filename: "CategoriasMunicipalidades.csv"
    url: "data/raw/CategoriasMunicipalidades.csv"
    read_options:
      format: "csv"
      header: true
      delimiter: ";"
      encoding: "utf-8-sig"

spark:
  app_name: "bronze-parcial"
  parquet_compression: "snappy"
  shuffle_partitions: 8
  timezone: "UTC"

profiling:
  sample_limit: 50000
  minimal: true

quality:
  pass_threshold: 0.98
  warning_threshold: 0.9

silver:
  partition_column: "year"
  required_government_level: "M"
  write_mode: "overwrite"
  quarantine_enabled: true

gold:
  partition_column: "year"
  write_mode: "overwrite"
  export_format: "parquet"

paths:
  raw: "data/raw"
  bronze: "data/bronze"
  silver: "data/silver"
  gold: "data/gold"
  reports: "reports"
